# Generated by Django 6.0.3 on 2026-04-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodules',
            name='video_duration_seconds',
            field=models.IntegerField(default=0, help_text='Video length in seconds — user must watch the full video'),
        ),
        migrations.AddField(
            model_name='coursemodules',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or video URL for this module section', null=True),
        ),
        migrations.AddField(
            model_name='quizattempts',
            name='current_section_order',
            field=models.IntegerField(default=1, help_text='For step-by-step quizzes, tracks which section the user is on'),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Which module/section this question belongs to (for step-by-step mode)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academy.coursemodules'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='step_by_step',
            field=models.BooleanField(default=False, help_text='If True, questions are presented section-by-section (VicRoads style). Each module = one section.'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='If True, this account cannot be deleted (for HR accounts)'),
        ),
        migrations.AddField(
            model_name='users',
            name='unique_lms_id',
            field=models.CharField(blank=True, help_text='Auto-generated ID like H1-rob, E3-jane', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('executive_hr', 'Executive HR'), ('hr', 'HR'), ('area_manager', 'Area Manager'), ('branch_manager', 'Branch Manager'), ('educator', 'Educator')], default='educator', max_length=20),
        ),
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('watch_video', 'Watch Video'), ('answer_questions', 'Answer Questions'), ('passed', 'Passed'), ('failed', 'Failed - Retry Required')], default='locked', max_length=20)),
                ('video_watched', models.BooleanField(default=False)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to='academy.quizattempts')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academy.coursemodules')),
            ],
            options={
                'db_table': 'section_progress',
                'ordering': ['module__sort_order'],
                'managed': True,
                'unique_together': {('attempt', 'module')},
            },
        ),
    ]
